name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node and cache
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Deploy to Github Pages
        run: |
          # Set CI to empty or else warnings will be treated as errors
          CI= yarn build
          echo fondsontran.com > build/CNAME
          touch build/.nojekyll
          # Based on https://github.com/tschaub/gh-pages/issues/345
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d build -b gh-pages -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
